require("dotenv").config();
const express=require("express"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),cookieSession=require("cookie-session"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const app=express(),PORT=Number(process.env.PORT||3000),ROOT=__dirname,DATA=path.join(ROOT,"data");
const SITE=path.join(DATA,"site.json"),MESSAGES=path.join(DATA,"messages.json");fs.mkdirSync(DATA,{recursive:true});
if(process.env.NODE_ENV==="production"){const need=["DISCORD_CLIENT_ID","DISCORD_CLIENT_SECRET","DISCORD_REDIRECT_URI","ADMIN_USER_IDS","SESSION_SECRET"];const missing=need.filter(k=>!process.env[k]);if(missing.length){console.error("Brak:",missing.join(", "));process.exit(1)}}
const admins=new Set((process.env.ADMIN_USER_IDS||"").split(",").map(x=>x.trim()).filter(Boolean));
app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'","data:","https:"],connectSrc:["'self'"],frameAncestors:["'none'"],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"]}}}));
app.use(express.urlencoded({extended:false,limit:"60kb"}));app.use(express.json({limit:"20kb"}));
app.use(cookieSession({name:"site_session",keys:[process.env.SESSION_SECRET||"dev-only-change-me"],httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:8*60*60*1000}));
const limiter=rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false});
const authLimiter=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:true,legacyHeaders:false});
const writeLimiter=rateLimit({windowMs:15*60*1000,limit:60,standardHeaders:true,legacyHeaders:false});app.use(limiter);
const read=(f,d)=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return d}};
function write(f,v){const t=f+"."+process.pid+"."+Date.now()+".tmp";fs.writeFileSync(t,JSON.stringify(v,null,2));fs.renameSync(t,f)}
function csrf(req){if(!req.session.csrf)req.session.csrf=crypto.randomBytes(32).toString("hex");return req.session.csrf}
function validCsrf(req){return typeof req.body._csrf==="string"&&req.body._csrf===req.session.csrf}
function admin(req,res,next){if(!req.session.user||!admins.has(req.session.user.id))return res.redirect("/admin/login");next()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

async function token(code){const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code,redirect_uri:process.env.DISCORD_REDIRECT_URI});const r=await fetch("https://discord.com/api/v10/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw Error("token");return r.json()}
async function me(at){const r=await fetch("https://discord.com/api/v10/users/@me",{headers:{Authorization:`Bearer ${at}`}});if(!r.ok)throw Error("user");return r.json()}
async function member(at,guild){const r=await fetch(`https://discord.com/api/v10/users/@me/guilds/${guild}/member`,{headers:{Authorization:`Bearer ${at}`}});if(!r.ok)return null;return r.json()}

function page(title,body,req){const c=csrf(req);return `<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><link rel="stylesheet" href="/admin/admin.css"></head><body><div class="shell"><aside><div class="brand">NOVA ADMIN</div><a href="/admin">Dashboard</a><a href="/admin/editor">Edytor strony</a><a href="/admin/messages">Wiadomości</a><a href="/" target="_blank">Podgląd ↗</a><form method="post" action="/admin/logout"><input type="hidden" name="_csrf" value="${esc(c)}"><button>Wyloguj</button></form></aside><main>${body}</main></div></body></html>`}

app.get("/auth/discord",authLimiter,(req,res)=>{const state=crypto.randomBytes(24).toString("hex");req.session.oauthState=state;const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||"",redirect_uri:process.env.DISCORD_REDIRECT_URI||"",response_type:"code",scope:"identify",state});res.redirect("https://discord.com/oauth2/authorize?"+p)})
app.get("/auth/discord/callback",authLimiter,async(req,res)=>{try{if(!req.query.code||!req.query.state||req.query.state!==req.session.oauthState)return res.status(400).send("Nieprawidłowy OAuth state.");delete req.session.oauthState;const t=await token(req.query.code),u=await me(t.access_token);if(!admins.has(u.id))return res.status(403).send("To konto Discord nie ma uprawnień administratora.");if(process.env.DISCORD_GUILD_ID){const m=await member(t.access_token,process.env.DISCORD_GUILD_ID);if(!m)return res.status(403).send("Nie jesteś na wymaganym serwerze Discord.");if(process.env.DISCORD_ADMIN_ROLE_ID&&!m.roles.includes(process.env.DISCORD_ADMIN_ROLE_ID))return res.status(403).send("Brak wymaganej roli Discord.")}req.session.user={id:u.id,username:u.username};req.session.csrf=crypto.randomBytes(32).toString("hex");res.redirect("/admin")}catch(e){console.error(e);res.status(500).send("Błąd logowania Discord.")}})
app.use("/admin",express.static(path.join(ROOT,"public-admin")));
app.get("/admin/login",(req,res)=>{if(req.session.user&&admins.has(req.session.user.id))return res.redirect("/admin");res.send(`<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Logowanie</title><link rel="stylesheet" href="/admin/admin.css"></head><body><div class="login"><div class="login-card"><div class="brand">NOVA ADMIN</div><h1>Panel administratora</h1><p>Logowanie jest obsługiwane przez Discord OAuth2.</p><a class="discord" href="/auth/discord">Zaloguj przez Discord</a><small>Hasło Discord nie jest przekazywane tej stronie.</small></div></div></body></html>`)});
app.get("/admin",admin,(req,res)=>{const s=read(SITE,{}),m=read(MESSAGES,[]);res.send(page("Dashboard",`<div class="top"><div><div class="eyebrow">PANEL ADMINISTRATORA</div><h1>Witaj, ${esc(req.session.user.username)}</h1><p>Zarządzaj treścią strony bez edytowania kodu.</p></div><div class="pill">Discord ID: ${esc(req.session.user.id)}</div></div><div class="grid"><div class="stat"><b>${s.services?.length||0}</b><span>usług</span></div><div class="stat"><b>${s.features?.length||0}</b><span>sekcji</span></div><div class="stat"><b>${m.length}</b><span>wiadomości</span></div></div><div class="panel"><h2>Szybkie akcje</h2><div class="actions"><a class="button" href="/admin/editor">Edytuj stronę</a><a class="button ghost" href="/" target="_blank">Otwórz stronę</a></div></div>`,req))});
app.get("/admin/editor",admin,(req,res)=>{const json=JSON.stringify(read(SITE,{}),null,2);res.send(page("Edytor",`<div class="top"><div><div class="eyebrow">EDYTOR</div><h1>Treść strony</h1><p>Zmieniaj dane w JSON. Panel sprawdza poprawność przed zapisem.</p></div></div><form method="post" action="/admin/editor" class="panel"><input type="hidden" name="_csrf" value="${esc(csrf(req))}"><textarea name="site" class="code" spellcheck="false">${esc(json)}</textarea><button class="button" type="submit">Zapisz zmiany</button></form>`,req))});
app.post("/admin/editor",admin,writeLimiter,(req,res)=>{if(!validCsrf(req))return res.status(403).send("Nieprawidłowy token CSRF.");if(typeof req.body.site!=="string"||req.body.site.length>60000)return res.status(400).send("Nieprawidłowe dane.");try{const v=JSON.parse(req.body.site);if(!v||typeof v!=="object"||Array.isArray(v))throw Error();write(SITE,v);res.redirect("/admin/editor?saved=1")}catch{res.status(400).send("Nie zapisano: sprawdź poprawność JSON.")}});
app.get("/admin/messages",admin,(req,res)=>{const m=read(MESSAGES,[]);const rows=m.slice().reverse().map(x=>`<article class="message"><div><b>${esc(x.name)}</b> <span>${esc(x.email)}</span><time>${esc(x.createdAt)}</time></div><p>${esc(x.message)}</p></article>`).join("")||"<p>Brak wiadomości.</p>";res.send(page("Wiadomości",`<div class="top"><div><div class="eyebrow">KONTAKT</div><h1>Wiadomości</h1></div></div><div class="panel">${rows}</div>`,req))});
app.post("/admin/logout",admin,(req,res)=>{if(!validCsrf(req))return res.status(403).send("Nieprawidłowy token CSRF.");req.session=null;res.redirect("/admin/login")});
app.get("/api/site",(req,res)=>{res.set("Cache-Control","no-store");res.json(read(SITE,{}))});
app.post("/api/contact",writeLimiter,(req,res)=>{const {name,email,message}=req.body||{};if(!name||!email||!message||String(name).length>100||String(email).length>200||String(message).length>3000)return res.status(400).json({error:"Nieprawidłowe dane."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email)))return res.status(400).json({error:"Nieprawidłowy e-mail."});const m=read(MESSAGES,[]);m.push({id:crypto.randomUUID(),name:String(name).trim(),email:String(email).trim(),message:String(message).trim(),createdAt:new Date().toISOString()});write(MESSAGES,m.slice(-500));res.json({ok:true})});
app.use(express.static(path.join(ROOT,"public")));app.use((req,res)=>res.status(404).send("404 — Nie znaleziono strony."));
app.listen(PORT,()=>console.log(`Server: http://localhost:${PORT}`));